name: CI
#Triggers
on:
  push:

#Etapas del pipeline
jobs:
  build:
    #Runners
    runs-on: ubuntu-latest

    steps:
      - name: Clonar codigo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@4.2.1
        with:
          java-version: '8'
          distribution: 'temurin'
          
      - name: Compile Maven Dependencies
        run: |
          mvn package
